/*Complete purchase order data dump for a given PO number*/
/*columns with a "m_" prefix are from pomast and "i_" are from poitem*/
DECLARE @PO varchar(60) SET @PO = ''
if (LEN(@PO)>0) BEGIN
	select m.fcompany AS m_fcompany,m.fcshipto AS m_fcshipto,m.forddate AS m_forddate,m.fpono AS m_fpono,m.fstatus AS m_fstatus,m.fvendno AS m_fvendno,m.fbuyer AS m_fbuyer,m.fchangeby AS m_fchangeby,m.fcngdate AS m_fcngdate,m.fconfirm AS m_fconfirm,m.fcontact AS m_fcontact,m.fcfname AS m_fcfname,m.fcreate AS m_fcreate,m.ffob AS m_ffob,m.fmethod AS m_fmethod,m.foldstatus AS m_foldstatus,m.fordrevdt AS m_fordrevdt,m.fordtot AS m_fordtot,m.fpayterm AS m_fpayterm,m.fpaytype AS m_fpaytype,m.fporev AS m_fporev,m.fprint AS m_fprint,m.freqdate AS m_freqdate,m.freqsdt AS m_freqsdt,m.freqsno AS m_freqsno,m.frevtot AS m_frevtot,m.fsalestax AS m_fsalestax,m.fshipvia AS m_fshipvia,m.ftax AS m_ftax,m.fcsnaddrke AS m_fcsnaddrke,m.fcsncity AS m_fcsncity,m.fcsnstate AS m_fcsnstate,m.fcsnzip AS m_fcsnzip,m.fcsncountr AS m_fcsncountr,m.fcsnphone AS m_fcsnphone,m.fcsnfax AS m_fcsnfax,m.fcshkey AS m_fcshkey,m.fcshaddrke AS m_fcshaddrke,m.fcshcompan AS m_fcshcompan,m.fcshcity AS m_fcshcity,m.fcshstate AS m_fcshstate,m.fcshzip AS m_fcshzip,m.fcshcountr AS m_fcshcountr,m.fcshphone AS m_fcshphone,m.fcshfax AS m_fcshfax,m.fnnextitem AS m_fnnextitem,m.fautoclose AS m_fautoclose,m.fcusrchr1 AS m_fcusrchr1,m.fcusrchr2 AS m_fcusrchr2,m.fcusrchr3 AS m_fcusrchr3,m.fnusrqty1 AS m_fnusrqty1,m.fnusrcur1 AS m_fnusrcur1,m.fdusrdate1 AS m_fdusrdate1,m.fccurid AS m_fccurid,m.fcfactor AS m_fcfactor,m.fdcurdate AS m_fdcurdate,m.fdeurodate AS m_fdeurodate,m.feurofctr AS m_feurofctr,m.fctype AS m_fctype,m.timestamp_column AS m_timestamp_column,m.identity_column AS m_identity_column,m.fmpaytype AS m_fmpaytype,m.fmshstreet AS m_fmshstreet,m.fmsnstreet AS m_fmsnstreet,m.fmusrmemo1 AS m_fmusrmemo1,m.fpoclosing AS m_fpoclosing,m.freasoncng AS m_freasoncng,m.fndbrmod AS m_fndbrmod,m.flpdate AS m_flpdate
	,i.fpono AS i_fpono,i.fpartno AS i_fpartno,i.frev AS i_frev,i.fmeasure AS i_fmeasure,i.fitemno AS i_fitemno,i.frelsno AS i_frelsno,i.fcategory AS i_fcategory,i.fsokey AS i_fsokey,i.fsoitm AS i_fsoitm,i.fsorls AS i_fsorls,i.fjokey AS i_fjokey,i.fjoitm AS i_fjoitm,i.fjoopno AS i_fjoopno,i.flstcost AS i_flstcost,i.fstdcost AS i_fstdcost,i.fleadtime AS i_fleadtime,i.forgpdate AS i_forgpdate,i.flstpdate AS i_flstpdate,i.fmultirls AS i_fmultirls,i.fnextrels AS i_fnextrels,i.fnqtydm AS i_fnqtydm,i.freqdate AS i_freqdate,i.fretqty AS i_fretqty,i.fordqty AS i_fordqty,i.fqtyutol AS i_fqtyutol,i.fqtyltol AS i_fqtyltol,i.fbkordqty AS i_fbkordqty,i.flstsdate AS i_flstsdate,i.frcpdate AS i_frcpdate,i.frcpqty AS i_frcpqty,i.fshpqty AS i_fshpqty,i.finvqty AS i_finvqty,i.fdiscount AS i_fdiscount,i.frework AS i_frework,i.fstandard AS i_fstandard,i.ftax AS i_ftax,i.fsalestax AS i_fsalestax,i.finspect AS i_finspect,i.flcost AS i_flcost,i.fucost AS i_fucost,i.fprintmemo AS i_fprintmemo,i.fvlstcost AS i_fvlstcost,i.fvleadtime AS i_fvleadtime,i.fvmeasure AS i_fvmeasure,i.fvpartno AS i_fvpartno,i.fvptdes AS i_fvptdes,i.fvordqty AS i_fvordqty,i.fvconvfact AS i_fvconvfact,i.fvucost AS i_fvucost,i.fqtyshipr AS i_fqtyshipr,i.fdateship AS i_fdateship,i.fparentpo AS i_fparentpo,i.frmano AS i_frmano,i.fdebitmemo AS i_fdebitmemo,i.finspcode AS i_finspcode,i.freceiver AS i_freceiver,i.fnorgucost AS i_fnorgucost,i.fcorgcateg AS i_fcorgcateg,i.fparentitm AS i_fparentitm,i.fparentrls AS i_fparentrls,i.frecvitm AS i_frecvitm,i.fnorgeurcost AS i_fnorgeurcost,i.fnorgtxncost AS i_fnorgtxncost,i.fueurocost AS i_fueurocost,i.futxncost AS i_futxncost,i.fvueurocost AS i_fvueurocost,i.fvutxncost AS i_fvutxncost,i.fljrdif AS i_fljrdif,i.fucostonly AS i_fucostonly,i.futxncston AS i_futxncston,i.fueurcston AS i_fueurcston,i.timestamp_column AS i_timestamp_column,i.identity_column AS i_identity_column,i.fcomments AS i_fcomments,i.fdescript AS i_fdescript,i.Fac AS i_Fac,i.fcbin AS i_fcbin,i.fcloc AS i_fcloc,i.fcudrev AS i_fcudrev,i.fndbrmod AS i_fndbrmod,i.blanketPO AS i_blanketPO,i.PlaceDate AS i_PlaceDate,i.DockTime AS i_DockTime,i.PurchBuf AS i_PurchBuf,i.Final AS i_Final,i.AvailDate AS i_AvailDate,i.SchedDate AS i_SchedDate
	FROM pomast m
	LEFT JOIN poitem i ON m.fpono = i.fpono
	where m.fpono like @PO
END